### ISSUE TITLE
M2: Bug in isNumberCorrect function

### ISSUE THREAD

**Issue by CamiloBorba09** [montevideo-tech/cmcd-validator#168]
A bug was found in the isNumberCorrect function. If the value of a key, which's type was 'number', was sent as 0, then the output of the validator would be 'not valid' with an error that the value is not a number when in reality it is. 

AC:
1. Fix the bug to include zero as a number.

**Comment by mcamardon** [comment]
While investigating AC #1 I encountered a bug in the isNumberCorrect function in the formatFunctions file. This bug was causing some wrong errors in the requests validation on the demo app. Due to this, this ticket is now dedicated to fixing the bug and the original one can now be found in https://github.com/montevideo-tech/cmcd-validator/issues/189
