### ISSUE TITLE
Simplify the rules of the standard

### ISSUE THREAD

**Issue by Unnil** [montevideo-tech/cmcd-validator#5]
Create a simplified list of the parameters that the standard has, with a brief explanation and accepted values.
This could be used as a shortcut for developers to better understand the standard instead of having to go and search for a paper or really long document describing the standard.

**Acceptance criteria**:
- Entry in the github wiki with the list of parameters of the standard, its accepted values and a brief explanation
- Add the result to the wiki

**Comment by gdavila** [comment]
Coping 3.3 section  of [CTA-5004](https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5004-final.pdf) should be enough to give and overview of the metrics.

**Comment by mcamardon** [comment]
I made a summary of the chart mentioned by gdavila to facilitate the reading of it. 

This chart shows the parameters that each of the keys must comply. Not every key featured in the standard can be found in the following chart, as some of them don't have any specific parameters except from the header and the type. This is just meant as a summary of the table displayed on the standard to facilitate the reading. Any further information regarding this can be found in https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5004-final.pdf. 


![Image](https://user-images.githubusercontent.com/124176760/218152089-1183db43-a816-48ba-8f76-e88b4e1d0a85.png)

**Comment by mcamardon** [comment]
Another thing to take into consideration are the payload definitions for the JSON and the Header/Query Argument transmittions. Again, this is a summary of section 3.2 of the standard to facilitate the reading. Any further information regarding this can be found in https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5004-final.pdf.

**Payload definition for JSON transmission**:

1. Key names are reserved.  Custom key names MUST carry a hyphenated prefix.
2. All key names are case-sensitive.
3. type Token encoded as JSON String
4. type Decimal and Integer encoded as JSON Number
5. type Boolean encoded as JSON Boolean
6. All keys are OPTIONAL.

**Payload definition for Headers and Query Argument transmission**

1. All information in the payload MUST be represented as <key>=<value> pairs.
2. Key-value pairs MUST be separated by = (Unicode 0x3D), except if the type is Boolean. In this case, if the value is TRUE, omit the = and the value.
3. Successive key/value pairs MUST be delimited by a comma Unicode 0x2C
4. Key names are reserved.
	Custom key names MUST carry a hyphenated prefix. 
5. For header transmittion, the defined headers are:
	- CMCD-Request: keys whose values vary with each request. 
	- CMCD-Object: keys whose values vary with the object being requested. 
	- CMCD-Status: keys whose values do not vary with every request or object. 
	- CMCD-Session: keys whose values are expected to be invariant over the life of the session.
6. All key names are case-sensitive
7. Type String require "" (Unicode 0x22). Double quotes and backslashes must be escaped by \ (Unicode 0x5C). Type Token does not require quoting.
8. All keys are optional.
9. For query argument, payload must be URLEncoded. Header MUST NOT be URLEncoded.


For both definitions, key-value pairs SHOULD be sequenced in alphabetical order of the key name in order to reduce the fingerprinting surface exposed by the player.

**Comment by mcamardon** [comment]
All this information has also been added to the wiki page https://github.com/montevideo-tech/cmcd-validator/wiki/Rules-of-sections-3.1,-3.2-and-3.3-of-CTA-5004.

**Comment by CamiloBorba09** [comment]
This ticket is done.

@pollingerMaxi , @arrivillagaTomas , @sebastianpiq . Could you check this [wiki](https://github.com/montevideo-tech/cmcd-validator/wiki/Rules-of-sections-3.1,-3.2-and-3.3-of-CTA-5004.)? Is it clear for you? Do we need to add something else? Tomorrow we are going to move this ticket to done.
